x-rails-environment: &rails_environment
  environment:
    - RAILS_ENV=development
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: rails-example
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3003:3000"
    depends_on:
      - db
    <<: [*rails_environment]
